# Generated by Django 5.2 on 2025-04-26 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cargo', models.CharField(default='Operador', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='TEMP-CODIGO', max_length=50, unique=True)),
                ('descricao', models.TextField(default='Sem descrição')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('usuario', models.CharField(default='Sistema', max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ControleEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('EM_USO', 'Em Uso'), ('FORNECIDO', 'Fornecido'), ('DEVOLVIDO', 'Devolvido'), ('DANIFICADO', 'Danificado'), ('PERDIDO', 'Perdido')], default='EMPRESTADO', max_length=15)),
                ('observacao_devolucao', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.equipamento')),
            ],
        ),
    ]
