# Generated by Django 5.2 on 2025-04-26 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleepi',
            name='data_prevista_devolucao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
