# Generated by Django 5.2 on 2025-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_alter_controleepi_data_prevista_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleepi',
            name='teste_data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
