# Generated by Django 5.2 on 2025-04-26 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_controleepi_teste_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleepi',
            name='data_entrega',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='controleepi',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='controleepi',
            name='status',
            field=models.CharField(blank=True, choices=[('EMPRESTADO', 'Emprestado'), ('EM_USO', 'Em Uso'), ('FORNECIDO', 'Fornecido'), ('DEVOLVIDO', 'Devolvido'), ('DANIFICADO', 'Danificado'), ('PERDIDO', 'Perdido')], default='EMPRESTADO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='controleepi',
            name='teste_data',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
